version: 2.1
orbs: 
  node: circleci/node@5.1.0
jobs:
  build_and_test:
    executor: node/default
    resource_class: small
    parallelism: 5
    steps:
      - checkout
      - node/install-packages
      - run: 
          name: Create folder for test results
          command: mkdir ~/testresults
      - run: mkdir no_files_here
      - run: 
          name: Run tests
          command: 
              TEST=$(circleci tests glob "__test__/*.js")
              circleci tests run --command="xargs pytest -o junit_family=legacy --junitxml=junit.xml" --verbose --split-by=timings
              # npm test $TEST
              
      - run:
          command: cp junit.xml ~/testresults/
          when: always
      - store_test_results:
                path: ~/testresults
      - store_artifacts:
                path: ~/testresults
      - persist_to_workspace:
                root: .
                paths:
                 - no_files_here
workflows:
  basic_workflow:
    jobs:
      - build_and_test
      
